version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: footbets_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=footbets
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=footbetsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
